// Prisma creates quoted PascalCase PostgreSQL identifiers. Keep this map aligned
// with prisma/schema.prisma; the chat agent uses it to generate safe SQL.
const databaseSchema = {
  User: { description: 'Authentication and staff accounts.', primaryKey: 'id', columns: { id: 'User ID', username: 'Login name', email: 'Account email', role: 'STUDENT, FACULTY, ADMIN, DRIVER and other role', status: 'Account status', createdAt: 'Created time' } },
  Department: { description: 'Academic departments.', primaryKey: 'id', columns: { id: 'Department ID', departmentCode: 'Department code', departmentName: 'Department name', officeEmail: 'Office email', building: 'Building' } },
  Program: { description: 'Academic programmes.', primaryKey: 'id', foreignKeys: { departmentId: 'Department.id' }, columns: { id: 'Programme ID', programCode: 'Programme code', programName: 'Programme name', degreeType: 'Degree type', departmentId: 'Owning department', durationYears: 'Duration', totalSemesters: 'Semester count' } },
  Student: { description: 'Student profiles and enrolment.', primaryKey: 'id', foreignKeys: { userId: 'User.id', departmentId: 'Department.id', programId: 'Program.id' }, columns: { id: 'Student ID', enrollmentNo: 'Enrolment number', firstName: 'First name', lastName: 'Last name', email: 'Student email', departmentId: 'Department', programId: 'Programme', admissionYear: 'Admission year', currentYear: 'Current year', currentSemester: 'Current semester', section: 'Section', status: 'Student status' } },
  Faculty: { description: 'Faculty profiles.', primaryKey: 'id', foreignKeys: { userId: 'User.id', departmentId: 'Department.id' }, columns: { id: 'Faculty ID', employeeId: 'Employee ID', firstName: 'First name', lastName: 'Last name', email: 'Faculty email', departmentId: 'Department', designation: 'Designation', specialization: 'Specialization', status: 'Status' } },
  Course: { description: 'Courses offered by programmes.', primaryKey: 'id', foreignKeys: { departmentId: 'Department.id', programId: 'Program.id' }, columns: { id: 'Course ID', courseCode: 'Course code', courseName: 'Course name', departmentId: 'Department', programId: 'Programme', semester: 'Semester', credits: 'Credits', courseType: 'Course type', status: 'Status' } },
  CourseFaculty: { description: 'Faculty course assignments.', primaryKey: 'id', foreignKeys: { courseId: 'Course.id', facultyId: 'Faculty.id' }, columns: { id: 'Assignment ID', courseId: 'Course', facultyId: 'Faculty', academicYear: 'Academic year', semester: 'Semester', section: 'Section', isPrimary: 'Primary faculty flag' } },
  Building: { description: 'Campus buildings.', primaryKey: 'id', columns: { id: 'Building ID', buildingCode: 'Building code', buildingName: 'Building name', numberOfFloors: 'Floor count', status: 'Status' } },
  Classroom: { description: 'Classrooms and labs.', primaryKey: 'id', foreignKeys: { buildingId: 'Building.id' }, columns: { id: 'Classroom ID', buildingId: 'Building', roomNumber: 'Room number', roomName: 'Room name', floor: 'Floor', capacity: 'Capacity', roomType: 'Room type', hasWifi: 'Wi-Fi availability' } },
  Timetable: { description: 'Scheduled classes.', primaryKey: 'id', foreignKeys: { courseId: 'Course.id', facultyId: 'Faculty.id', classroomId: 'Classroom.id', programId: 'Program.id' }, columns: { id: 'Timetable ID', courseId: 'Course', facultyId: 'Faculty', classroomId: 'Classroom', programId: 'Programme', section: 'Section', semester: 'Semester', dayOfWeek: 'Day', startTime: 'Start time', endTime: 'End time', academicYear: 'Academic year' } },
  AttendanceSession: { description: 'Attendance-taking class sessions.', primaryKey: 'id', foreignKeys: { courseId: 'Course.id', facultyId: 'Faculty.id', classroomId: 'Classroom.id' }, columns: { id: 'Session ID', courseId: 'Course', facultyId: 'Faculty', classroomId: 'Classroom', date: 'Class date', attendanceMethod: 'QR, GPS, BLE, FACE or MANUAL', status: 'Session status' } },
  AttendanceRecord: { description: 'Individual attendance records.', primaryKey: 'id', foreignKeys: { sessionId: 'AttendanceSession.id', studentId: 'Student.id' }, columns: { id: 'Record ID', sessionId: 'Attendance session', studentId: 'Student', status: 'PRESENT, ABSENT, LATE or EXCUSED', markedAt: 'Marked time', verificationMethod: 'Verification method' } },
  Bus: { description: 'Campus transport buses, including current GPS and service details.', primaryKey: 'id', columns: { id: 'Bus ID', busNumber: 'Campus bus number', registrationNumber: 'Vehicle registration number', vehicleModel: 'Vehicle model', manufacturer: 'Manufacturer', manufacturingYear: 'Year manufactured', capacity: 'Total capacity', seatingCapacity: 'Seating capacity', busType: 'AC, NON_AC or MINI', fuelType: 'DIESEL, PETROL, CNG or ELECTRIC', currentLatitude: 'Current GPS latitude', currentLongitude: 'Current GPS longitude', currentSpeed: 'Current speed', lastLocationUpdate: 'GPS update time', status: 'Operational status', insuranceExpiry: 'Insurance expiry', nextServiceDate: 'Next service date' } },
  Route: { description: 'Campus bus routes.', primaryKey: 'id', columns: { id: 'Route ID', routeCode: 'Route code', routeName: 'Route name', startPoint: 'Starting point', endPoint: 'End point', totalDistance: 'Distance in km', estimatedDuration: 'Duration in minutes', status: 'Route status' } },
  BusStop: { description: 'Stops within bus routes.', primaryKey: 'id', foreignKeys: { routeId: 'Route.id' }, columns: { id: 'Stop ID', stopCode: 'Stop code', stopName: 'Stop name', address: 'Address', routeId: 'Route', stopOrder: 'Stop sequence', estimatedArrivalTime: 'Estimated arrival', status: 'Status' } },
  BusTrip: { description: 'Scheduled or completed bus trips.', primaryKey: 'id', foreignKeys: { busId: 'Bus.id', routeId: 'Route.id', driverId: 'Driver.id' }, columns: { id: 'Trip ID', busId: 'Bus', routeId: 'Route', driverId: 'Driver', tripDate: 'Trip date', tripType: 'MORNING, EVENING or SPECIAL', scheduledDeparture: 'Scheduled departure', actualDeparture: 'Actual departure', status: 'Trip status' } },
  Book: { description: 'Library book titles.', primaryKey: 'id', columns: { id: 'Book ID', isbn: 'ISBN', title: 'Title', author: 'Author', category: 'Category', totalCopies: 'Total copies', availableCopies: 'Available copies', status: 'Status' } },
  BookCopy: { description: 'Individual library copies.', primaryKey: 'id', foreignKeys: { bookId: 'Book.id' }, columns: { id: 'Copy ID', bookId: 'Book', accessionNumber: 'Accession number', condition: 'Copy condition', status: 'AVAILABLE, ISSUED and other status' } },
  FeeStructure: { description: 'Programme fee structures.', primaryKey: 'id', foreignKeys: { programId: 'Program.id' }, columns: { id: 'Fee structure ID', programId: 'Programme', academicYear: 'Academic year', semester: 'Semester', tuitionFee: 'Tuition fee', totalFee: 'Total fee', dueDate: 'Due date' } },
  StudentFee: { description: 'Student fee balances.', primaryKey: 'id', foreignKeys: { studentId: 'Student.id', feeStructureId: 'FeeStructure.id' }, columns: { id: 'Student fee ID', studentId: 'Student', feeStructureId: 'Fee structure', amountDue: 'Amount due', amountPaid: 'Amount paid', balance: 'Outstanding balance', dueDate: 'Due date', status: 'Fee status' } },
  Notice: { description: 'Campus notices.', primaryKey: 'id', foreignKeys: { createdById: 'User.id' }, columns: { id: 'Notice ID', title: 'Title', content: 'Content', createdById: 'Creator', targetRole: 'Audience role', priority: 'Priority', publishedAt: 'Publication date', status: 'Status' } },
  Event: { description: 'Campus events.', primaryKey: 'id', foreignKeys: { organizerId: 'User.id' }, columns: { id: 'Event ID', title: 'Title', description: 'Description', venue: 'Venue', organizerId: 'Organizer', startDatetime: 'Start', endDatetime: 'End', status: 'Event status' } },
  MenuItem: { description: 'Canteen menu items.', primaryKey: 'id', columns: { id: 'Menu item ID', name: 'Item name', category: 'Menu category', price: 'Price', available: 'Availability' } },
  Company: { description: 'Placement companies.', primaryKey: 'id', columns: { id: 'Company ID', companyName: 'Company name', industry: 'Industry', website: 'Website' } },
  JobDrive: { description: 'Placement job drives.', primaryKey: 'id', foreignKeys: { companyId: 'Company.id' }, columns: { id: 'Job drive ID', companyId: 'Company', jobTitle: 'Job title', location: 'Location', salaryPackage: 'Salary package', minimumCgpa: 'Minimum CGPA', applicationDeadline: 'Deadline', status: 'Job status' } },
  CampusLocation: { description: 'Campus points of interest.', primaryKey: 'id', foreignKeys: { buildingId: 'Building.id', classroomId: 'Classroom.id' }, columns: { id: 'Location ID', name: 'Location name', category: 'Location category', buildingId: 'Building', classroomId: 'Classroom', floor: 'Floor', description: 'Location guidance', openingTime: 'Opening time', closingTime: 'Closing time' } },
};

module.exports = { databaseSchema };
